spring:
  application:
    name: backend-web

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:56010/cmo_connect
    username: CMO
    password: CMO_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    basic:
      enabled: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

server:
  ssl:
    enabled: false

debug: true
